add dm-verity support for cic
projectceladon/vendor-intel-cic pull request #104
Opened 2020-04-22 01:10 UTC by syan10

currently the dm-verity only for the system.img.
At build stage, will generate the verity_metadata which format is like this below
{roothash_size|roothash|hashtree_size|hashtree}.
At install stage, if w/ "-s" option, it will parse the verity_metadata to get the
hashtree and that will be pushed into aic-manager together with the metadata image
(do this in install stage because it will cost some times...)
At start stage, if there find the verity_metadta, then try to get the roothash from
the metadata and create the dm device for system.img

Tracked-On: OAM-89713
Signed-off-by: Yan, Shaopu <shaopu.yan@intel.com>

2020-04-22 03:30 UTC, sysopenci reviewed
Autobuild started from pull-request-changes on this PR.

Cactus automatically verified this PR.

For more information, see: /absp/builders/celadon_pmr0_cic-autobuild/builds/444

2020-04-27 00:46 UTC, kaushlen approved these changes

2020-04-27 01:02 UTC, kwang13 approved these changes

2020-04-27 01:07 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp/builders/celadon_pmr0_cic-preintegration/builds/424

2020-04-27 02:46 UTC, joez approved these changes
LGTM

2020-04-27 02:52 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp/builders/celadon_pmr0_cic-preintegration/builds/425

2020-04-27 03:03 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp/builders/celadon_pmr0_cic-preintegration/builds/426

2020-04-27 03:12 UTC, JeevakaPrabu requested changes

2020-04-27 03:12 UTC, JeevakaPrabu commented on host/docker/aic-manager/scripts/image-entry
> +        if [[ $name = "system" && -f "$SYSTEM_VERITY_IMAGE" ]]
Clarification needed on this if

2020-04-27 04:55 UTC, sysopenci reviewed
Autobuild started from pull-request-changes on this PR.

FAILURE: CheckBug Bad comments/Bugs

For more information, see: /absp/builders/celadon_pmr0_cic-autobuild/builds/451

2020-04-27 05:25 UTC, JeevakaPrabu approved these changes

2020-04-27 06:17 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp/builders/celadon_pmr0_cic-preintegration/builds/427

Done by "Yan, Shaopu" <shaopu.yan@intel.com>

2020-04-27 06:18 UTC, sysopenci reviewed
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp/builders/celadon_pmr0_cic-premerge/builds/136

Done by "Yan, Shaopu" <shaopu.yan@intel.com>

2020-04-27 07:55 UTC, merged

2020-04-27 07:56 UTC, sysopenci reviewed
cactus finished building and testing your changes 

It was requested for merge by "Yan, Shaopu" <shaopu.yan@intel.com> 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp/builders/celadon_pmr0_cic-mergerequest/builds/186